### ISSUE TITLE
all games to zero 

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/Blum#2]
[Blum] | 2024-11-16 10:28:17 | SUCCESS  | 518 - Name | Successfully start game! - ID: b3bfb0fa-8b44-4db1-adf1-6d01de0ed9f3
Subprocess error: wasm://wasm/000e1a26:1

RuntimeError: unreachable
    at wasm://wasm/000e1a26:wasm-function[155]:0x29a55
    at wasm://wasm/000e1a26:wasm-function[220]:0x2c7d7
    at wasm://wasm/000e1a26:wasm-function[82]:0x1ae37
    at Object.getPayload (file:///home/tol/bots/Blum/bot/core/payload/gen2.mjs:210:21)
    at file:///home/tol/bots/Blum/bot/core/payload/blum.mjs:34:22

Node.js v18.19.1
[Blum] | 2024-11-16 10:28:17 | INFO     | 677 - Name | Wait 30 seconds to complete game!...
{"message":"cannot decrypt claim payload"}
[Blum] | 2024-11-16 10:28:48 | WARNING  | 554 - Name | Failed to claim game: 500

**Comment by vanhbakaa** [comment]
??? 
![image](https://github.com/user-attachments/assets/870c4fd4-564e-4b88-8879-6144a377227f)
